### ISSUE TITLE
pthread_create not found when cmake

### ISSUE THREAD

**Issue by littlepig2013** [Microsoft/FASTER#31] opened 2018-09-17 19:24 UTC
The cmake command under the build/Debug directory failed in my machine.

The cmake version I use is 3.5.1

Here is the CMakeError.log:

Run Build Command:"/usr/bin/make" "cmTC_d8de1/fast"
/usr/bin/make -f CMakeFiles/cmTC_d8de1.dir/build.make CMakeFiles/cmTC_d8de1.dir/build
make[1]: Entering directory '/home/ubuntu/FASTER_TEST/FASTER/cc/build/Debug/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_d8de1.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_d8de1.dir/CheckSymbolExists.c.o   -c /home/ubuntu/FASTER_TEST/FASTER/cc/build/Debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_d8de1
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d8de1.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_d8de1.dir/CheckSymbolExists.c.o  -o cmTC_d8de1 -rdynamic
CMakeFiles/cmTC_d8de1.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_d8de1.dir/build.make:97: recipe for target 'cmTC_d8de1' failed
make[1]: *** [cmTC_d8de1] Error 1
make[1]: Leaving directory '/home/ubuntu/FASTER_TEST/FASTER/cc/build/Debug/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_d8de1/fast' failed
make: *** [cmTC_d8de1/fast] Error 2

File /home/ubuntu/FASTER_TEST/FASTER/cc/build/Debug/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

I also checked part of the output in the terminal:

-- Found PythonInterp: /usr/bin/python (found version "2.7.12")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes

which said that pthread is found but pthread_create is not found.

How should I do to cmake successfully?

**Comment by littlepig2013** [comment] 2018-09-17 19:38
My machine's system is Ubuntu 16.04.5 LTS.

**Comment by jahunter-m** [comment] 2018-09-19 17:30
Looks to me like it's fine for cmake not to find function pthread_create(). Also, file CheckSymbolExists.c is supposed to tell whether the symbol ("pthread_create()") exists. The problem seems to be that cmake is returning an error ("undefined symbol...") rather than capturing the error and detecting that the symbol does not exist. So, file CheckSymbolExists.c does not seem to be working correctly...

Both the failing and succeeding cases use cmake 3.5.1.

**Comment by jahunter-m** [comment] 2018-09-19 17:41
In my working build, I also see a CMakeFiles/CmakeError.log, with the same contents pasted above. However, the cmake build works fine. (Try running "make" after running the cmake command.) I am closing this as not a bug; please reopen if the build doesn't work.

**Closed by jahunter-m** 2018-09-19 17:41 UTC

**Comment by littlepig2013** [comment] 2018-09-19 17:43
Yes. It is also fine for me even it can't find pthread_create() because at least the interfaces in FASTER I've used can work now. So far we've seen that this file doesn't work correctly during cmake. What I'm worried about is that whether this file influences anything else?
