### ISSUE TITLE
Unexpected token in release mode. C#

### ISSUE THREAD

**Issue by diegotormes** [Microsoft/FASTER#33] opened 2018-09-27 14:54 UTC
PS C:\Fuentes\Faster\cs\playground\SumStore\bin\x64\Release> .\SumStore.exe single populate

Excepción no controlada: System.Exception: Errors during code-gen compilation:
C:\Users\Diego\AppData\Local\Temp\FASTER\xn0h51qp\PersistentMemoryMalloc.cs(85,49): error CS1073: Unexpected token ','
   en FASTER.core.Roslyn.FasterHashTableCompiler`7.GenerateFasterHashTableClass(Boolean persistGeneratedCode, Boolean optimizeCode, Int64 LogTotalSizeBytes, Double LogMutableFraction, Int32 LogPageSizeBits) en C:\Fuentes\Faster\cs\src\core\Codegen\FasterHashTableCompiler.cs:línea 59
   en FASTER.core.HashTableManager.GetFasterHashTable[TKey,TValue,TInput,TOutput,TContext,TFunctions,TIFaster](Int64 size, IDevice logDevice, IDevice objectLogDevice, String checkpointDir, Int64 LogTotalSizeBytes, Double LogMutableFraction, Int32 LogPageSizeBits, Boolean persistDll, Boolean optimizeCode) en C:\Fuentes\Faster\cs\src\core\Codegen\HashTableManager.cs:línea 32
   en SumStore.SingleThreadedRecoveryTest..ctor() en C:\Fuentes\Faster\cs\playground\SumStore\SingleThreadedRecoveryTest.cs:línea 25
   en SumStore.Program.Main(String[] args) en C:\Fuentes\Faster\cs\playground\SumStore\Program.cs:línea 30
PS C:\Fuentes\Faster\cs\playground\SumStore\bin\x64\Release>

**Comment by badrishc** [comment] 2018-10-04 15:48
Looks like a duplicate of #11 - see workaround there.

**Closed** 2018-10-04 15:48 UTC
