### ISSUE TITLE
Is it possible to read locally generated logs from Azure?

### ISSUE THREAD

**Issue by smolatom** [microsoft/FASTER#495] opened 2021-06-09 15:26 UTC
Hi, I have a question, depending on the answer it might be a bug.

The question: Is it possible to log data locally (generate segment/commit files locally), upload the files to blobs and then read the data using Azure-based classes (`AzureStorageDevice`, `AzureStorageNamedDeviceFactory`)?

My scenario is as follows:

1. Log data locally
2. Take the segment/commit files and upload them to blobs
3. Read the data directly from the blobs

The below code is what I do to create an Azure based FasterLog instance.

```
var device = new AzureStorageDevice(connectionString, containerName, directoryName, blobName);

var deviceFactory = new AzureStorageNamedDeviceFactory(connectionString);
var checkpointNamingScheme = new DefaultCheckpointNamingScheme($"{containerName}/{directoryName}");
var logCommitManager = new DeviceLogCommitCheckpointManager(
    deviceFactory,
    checkpointNamingScheme);

_log = new FasterLog(new FasterLogSettings { LogDevice = device, LogCommitManager = logCommitManager });
```

What I've been able to found out so far is that in such scenario `_log.BeginAddess` and `_log.FlushedUntilAddress` are the same. The iterator (see below) gets stuck then.

```
using var iterator = _log.Scan(
                _log.BeginAddress,
                _log.FlushedUntilAddress,
                null,
                false,
                ScanBufferingMode.DoublePageBuffering,
                scanUncommitted: scanUncommitted);
```

**Comment by badrishc** [comment] 2021-06-10 03:27
This could be because the manual upload creates BlockBlobs, whereas FASTER when writing/reading directly using AzureStorageDevice, writes PageBlobs.

**Comment by badrishc** [comment] 2021-06-10 04:58
Confirmed that this is the reason. Try to upload as page blob, or it should be fairly easy for you to extend AzureStorageDevice to work with block blobs.

**Comment by badrishc** [comment] 2021-06-11 02:31
Created issue to track this, closing.

**Closed by badrishc** 2021-06-11 02:31 UTC

**Comment by smolatom** [comment] 2021-06-11 07:22
In the end we were able to proceed. I'll write here if I find some time to play a bit more with the code and find something worth sharing.

**Comment by badrishc** [comment] 2021-06-11 13:33
How did you proceed? Was the issue what I said, or something else?

**Comment by smolatom** [comment] 2021-06-14 12:30
It was most likely an issue on our side - a wrong path to the blobs. For some reason I expected an exception to be thrown when the log doesn't fine segment/commit blobs at the given path. Yep, it was a wrong assumption.

**Comment by badrishc** [comment] 2021-06-14 17:53
That is odd -- when I tried to repro your scenario, it did not work for me either. But that seemed to be because Azure Storage Explorer uploads the files as block blobs, which are not supported by `AzureStorageDevice`. The paths were correct in my case.
