### ISSUE TITLE
[C#] UnCommit Log Scan

### ISSUE THREAD

**Issue by qinxg** [microsoft/FASTER#255] opened 2020-03-09 16:42 UTC
Enqueu Some Log into Fasterlog But not Commit 

Now I Scan it..   Is null...

How Can I Scan Memory Log???

![image](https://user-images.githubusercontent.com/1769735/76236591-e0269580-6267-11ea-87ed-f586ac808d6c.png)

**Comment by badrishc** [comment] 2020-03-09 18:35
The scan is by design restricted to scan only committed data because that is the normal use case for a persistent log. Users typically do not want to scan uncommitted data. What is the use case to scan uncommitted data?

As a workaround, just comment out the second part of the if condition here: https://github.com/microsoft/FASTER/blob/26569b223cdc5da62f9364c921d00a2201767bf1/cs/src/core/Index/FasterLog/FasterLogIterator.cs#L443

**Comment by tpajurek-dtml** [comment] 2020-08-07 13:55
Hello  @badrishc ,

we have also run into a use-case that requires such behavior.

We would like to use Faster Log basically as a queue between producer and consumer in the following way:

* We do not mind losing some data in case of failures (so it is good enough to commit at some intervals). 
* We expect that consumer will be faster than producer in most cases (therefore the log is usually almost empty).
* We would like to minimize writing to disk - in our case, we wouldn't need to write most of the data because they care consumed immediately after enqueuing.
* Sometimes it can happen that consumer is unable to process the data for a longer period of time and therefore the log starts to filling up. In this case, we would like to spill the data to the disk periodically.

I have tried to comment out the second part of condition as you propose but it looks like it does not work. We observe that when such code modification is done, the `GetAsyncEnumerable` returns only the first message and than blocks and does not return anymore messages if they are commited.

Is there an another way how to achieve the desired behavior?

We are using this code to test it out:

```csharp
class Program
{
    static async Task Main(string[] args)
    {
        var device = Devices.CreateLogDevice($"<path>");

        var log = new FasterLog(new FasterLogSettings { LogDevice = device });

        using var cts = new CancellationTokenSource();

        var producer = ProducerAsync(log, cts.Token);
        var commiter = CommiterAsync(log, cts.Token);
        var consumer = ConsumerAsync(log, cts.Token);

        Console.CancelKeyPress += (o, eventArgs) =>
        {
            Console.WriteLine("Cancelling program...");
            eventArgs.Cancel = true;
            cts.Cancel();
        };

        await producer;
        await consumer;
        await commiter;

        Console.WriteLine("Finished.");

    }

    static async Task CommiterAsync(FasterLog log, CancellationToken cancellationToken)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            await Task.Delay(TimeSpan.FromSeconds(8), cancellationToken);

            Console.WriteLine("Committing...");

            await log.CommitAsync();
        }
    }

    static async Task ProducerAsync(FasterLog log, CancellationToken cancellationToken)
    {
        var i = 0L;
        while (!cancellationToken.IsCancellationRequested)
        {
            Console.WriteLine($"Producing {i}");

            log.Enqueue(Encoding.UTF8.GetBytes(i.ToString()));

            i++;

            await Task.Delay(TimeSpan.FromSeconds(2));
        }
    }

    static async Task ConsumerAsync(FasterLog log, CancellationToken cancellationToken)
    {
        using var iter = log.Scan(log.BeginAddress, long.MaxValue, null, true, ScanBufferingMode.DoublePageBuffering);

        await foreach (var (result, length, currentAddress) in iter.GetAsyncEnumerable(cancellationToken))
        {
            Console.WriteLine($"Consuming {Encoding.UTF8.GetString(result)}");
        }
    }

}
```

**Comment by badrishc** [comment] 2020-08-12 05:46
Re-opening to track, based on recent comment. This requires some (but not much) code I think. We will respond with comments/ideas in the near future.

**Comment by badrishc** [comment] 2020-08-15 13:48
Is it okay if a record is available to be consumed only after the current page gets filled up? Since we allow multi threaded enqueue, a page might have holes until it's sealed eventually.

**Comment by tpajurek-dtml** [comment] 2020-08-16 14:25
>  if a record is available to be consumed only after the current page (or recent k pages) gets filled

Doesn't Faster Log already behave like this? According to the docs, I understand that when a page is filled up, it is automatically committed, therefore written to disk => readable by consumer.

From this perspective, what I mean is that in case that consumer is faster than producer enough, it manages to consume messages and trim them even before there are committed by producer or upon page is filled up -> therefore when producer eventually commits it should be no-op.

**Comment by badrishc** [comment] 2020-08-18 00:16
A rough solution is checked in here: https://github.com/microsoft/FASTER/pull/298

Because the "tail" of the log is unsafe to consume, I had to add a RefreshUncommitted() call to FasterLog. The idea is that producers call this periodically, whenever they want to expose the most recent tail to readers. This is slightly more expensive, so we do not automatically do it after every enqueue.

**Comment by badrishc** [comment] 2020-08-18 00:24
And this is the sample: https://github.com/microsoft/FASTER/blob/01e5487fd6c11b090494307060eaf9492ec1026c/cs/playground/FasterLogPubSub/Program.cs

**Comment by tpajurek-dtml** [comment] 2020-08-18 09:35
Great, seems like a good solution. I am not familiar with Faster internals, so I am not able to do thorough review but I at least went through the code and mark changes that I think I breaking to the public API.

Also, can I help with updating the documentation in GitHub pages?

**Comment by badrishc** [comment] 2020-08-25 00:24
Thank you. Sure, if you can help update the documentation that would be great!

**Closed** 2020-08-25 23:50 UTC

**Comment by tpajurek-dtml** [comment] 2020-09-05 15:35
I have create an PR with docs (#317).
